version: "3.7"
services:
  db:
    image: "mongo:latest"
    container_name: "mongodb"
    hostname: "mongodb"
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    networks:
      - project
    volumes:
      - "mongodb_data:/golang/"
    env_file: mongo.env

  person-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - project
    expose:
      - "8080"
    links:
      - db

networks:
  project:
    driver: bridge

volumes:
  mongodb_data:
    driver: local